"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.applications.mobilenet_v2 import (MobileNetV2,
                                                 decode_predictions,
                                                 preprocess_input)
