import collections

from keras.src import ops
from keras.src.backend.common.backend_utils import canonicalize_axis


def split_tensor_for_parallelism(tensor, index, device_count, dim):
    """Calculates a slice of a tensor along a specified dimension for a
    given index.

    This utility is used in tensor parallelism API to distribute a
    tensor across multiple devices.

    Args:
        tensor: The full tensor to be sharded.
        index: The index of the device/shard to return (e.g., 0, 1, 2...).
        device_count: The total number of parallel devices or splits.
        dim: The dimension along which to split the tensor. Supports negative
            indexing.

    Returns:
        A tensor slice corresponding to the given `index`.
    """
    # Ensure we are operating on a tensor (extracts value from Variables)
    if not isinstance(device_count, int) or device_count <= 0:
        raise ValueError(
            f"Invalid device_count value: {device_count}. "
            "Expected device_count to be a positive integer."
        )
    if not isinstance(index, int) or not (0 <= index < device_count):
        raise ValueError(
            f"Invalid index value: {index}. "
            f"Expected index to be an integer in the range [0, {device_count})."
        )
    tensor = ops.convert_to_tensor(tensor)

    split_dim = canonicalize_axis(dim, ops.ndim(tensor))

    splits = ops.array_split(
        tensor, indices_or_sections=device_count, axis=split_dim
    )
    return splits[index]


# Container for tracking rules generated by autoconfig.
# Distinguished from standard Keras LayoutMap by its structure (holds rule
# dictionaries, not direct variable-to-axis mappings).
ParallelLayoutMap = collections.namedtuple(
    "ParallelLayoutMap", ["state_rules", "output_rules"]
)
