path: "tensorflow.keras.regularizers.orthogonal_regularizer"
tf_class {
  is_instance: "<class \'keras.regularizers.OrthogonalRegularizer\'>"
  is_instance: "<class \'keras.regularizers.Regularizer\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'factor\', \'mode\'], varargs=None, keywords=None, defaults=[\'0.01\', \'rows\'], "
  }
  member_method {
    name: "from_config"
    argspec: "args=[\'cls\', \'config\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_config"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
