path: "tensorflow.keras.saving"
tf_module {
  member {
    name: "custom_object_scope"
    mtype: "<type \'type\'>"
  }
  member_method {
    name: "deserialize_keras_object"
    argspec: "args=[\'config\', \'custom_objects\', \'safe_mode\'], varargs=None, keywords=kwargs, defaults=[\'None\', \'True\'], "
  }
  member_method {
    name: "get_custom_objects"
    argspec: "args=[], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_registered_name"
    argspec: "args=[\'obj\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_registered_object"
    argspec: "args=[\'name\', \'custom_objects\', \'module_objects\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
  }
  member_method {
    name: "load_model"
    argspec: "args=[\'filepath\', \'custom_objects\', \'compile\', \'safe_mode\'], varargs=None, keywords=kwargs, defaults=[\'None\', \'True\', \'True\'], "
  }
  member_method {
    name: "register_keras_serializable"
    argspec: "args=[\'package\', \'name\'], varargs=None, keywords=None, defaults=[\'Custom\', \'None\'], "
  }
  member_method {
    name: "save_model"
    argspec: "args=[\'model\', \'filepath\', \'overwrite\', \'save_format\'], varargs=None, keywords=kwargs, defaults=[\'True\', \'None\'], "
  }
  member_method {
    name: "serialize_keras_object"
    argspec: "args=[\'obj\'], varargs=None, keywords=None, defaults=None"
  }
}
