"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.distillation.distiller import Distiller as Distiller
from keras.src.distillation.strategies import (
    DistillationLoss as DistillationLoss,
)
from keras.src.distillation.strategies import (
    FeatureDistillation as FeatureDistillation,
)
from keras.src.distillation.strategies import (
    LogitsDistillation as LogitsDistillation,
)
