"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.applications.mobilenet_v2 import MobileNetV2 as MobileNetV2
from keras.src.applications.mobilenet_v2 import (
    decode_predictions as decode_predictions,
)
from keras.src.applications.mobilenet_v2 import (
    preprocess_input as preprocess_input,
)
