"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.legacy.preprocessing.sequence import (TimeseriesGenerator,
                                                     make_sampling_table,
                                                     skipgrams)
from keras.src.utils.sequence_utils import pad_sequences
