"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.applications.inception_resnet_v2 import (InceptionResNetV2,
                                                        decode_predictions,
                                                        preprocess_input)
