"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.applications.lpips import LPIPS
from keras.src.applications.lpips import preprocess_input
