"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.quantizers import deserialize, get, serialize
from keras.src.quantizers.quantizers import (AbsMaxQuantizer, Quantizer,
                                             abs_max_quantize,
                                             compute_float8_amax_history,
                                             compute_float8_scale,
                                             quantize_and_dequantize)
