"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.activations import deserialize, get, serialize
from keras.src.activations.activations import (celu, elu, exponential, gelu,
                                               glu, hard_shrink, hard_sigmoid)
from keras.src.activations.activations import hard_silu
from keras.src.activations.activations import hard_silu as hard_swish
from keras.src.activations.activations import (hard_tanh, leaky_relu, linear,
                                               log_sigmoid, log_softmax, mish,
                                               relu, relu6, selu, sigmoid)
from keras.src.activations.activations import silu
from keras.src.activations.activations import silu as swish
from keras.src.activations.activations import (soft_shrink, softmax, softplus,
                                               softsign, sparse_plus,
                                               sparsemax, squareplus, tanh,
                                               tanh_shrink, threshold)
