# Description:
#   Contains Keras models to Estimator converter

# Placeholder: load unaliased py_library

package(
    # copybara:uncomment default_applicable_licenses = ["//keras:license"],
    default_visibility = [
        "//keras:friends",
    ],
    licenses = ["notice"],
)

py_library(
    name = "estimator",
    srcs = [
        "__init__.py",
    ],
    srcs_version = "PY3",
    deps = [
        "//:expect_tensorflow_installed",
    ],
)
