"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.applications.inception_v3 import InceptionV3 as InceptionV3
from keras.src.applications.inception_v3 import (
    decode_predictions as decode_predictions,
)
from keras.src.applications.inception_v3 import (
    preprocess_input as preprocess_input,
)
