"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.backend.common.dtypes import result_type
from keras.src.backend.common.global_state import clear_session
from keras.src.backend.common.keras_tensor import is_keras_tensor
from keras.src.backend.common.variables import (is_float_dtype, is_int_dtype,
                                                standardize_dtype)
from keras.src.backend.config import (backend, epsilon, floatx,
                                      image_data_format, set_epsilon,
                                      set_floatx, set_image_data_format)
from keras.src.utils.naming import get_uid
