"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.applications.xception import (Xception, decode_predictions,
                                             preprocess_input)
