"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.distribution.distributed_backend import (
    apply_gradients as apply_gradients,
)
from keras.src.distribution.distributed_backend import (
    create_optimizer as create_optimizer,
)
from keras.src.distribution.distributed_backend import (
    get_communication_ops as get_communication_ops,
)
from keras.src.distribution.distributed_backend import (
    get_device_info as get_device_info,
)
from keras.src.distribution.distributed_backend import (
    is_multi_device_capable as is_multi_device_capable,
)
from keras.src.distribution.distribution_lib import DataParallel as DataParallel
from keras.src.distribution.distribution_lib import DeviceMesh as DeviceMesh
from keras.src.distribution.distribution_lib import LayoutMap as LayoutMap
from keras.src.distribution.distribution_lib import (
    ModelParallel as ModelParallel,
)
from keras.src.distribution.distribution_lib import TensorLayout as TensorLayout
from keras.src.distribution.distribution_lib import (
    distribute_tensor as distribute_tensor,
)
from keras.src.distribution.distribution_lib import distribution as distribution
from keras.src.distribution.distribution_lib import initialize as initialize
from keras.src.distribution.distribution_lib import list_devices as list_devices
from keras.src.distribution.distribution_lib import (
    set_distribution as set_distribution,
)
