"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.ops.math import view_as_complex as view_as_complex
from keras.src.ops.math import view_as_real as view_as_real
