"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.legacy.saving.serialization import (deserialize_keras_object,
                                                   serialize_keras_object)
