'''Train a simple deep CNN on the CIFAR10 small images dataset.

It gets to 75% validation accuracy in 25 epochs, and 79% after 50 epochs.
(it's still underfitting at that point, though).
'''

from __future__ import print_function
import keras.backend as K
import keras
from keras import Input, Model
from keras.datasets import cifar10
from keras.layers.transfer import MMD
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
import os

# import sys
# sys.path.append("pycharm-debug.egg")
# import pydevd
# pydevd.settrace('localhost', port=12345, stdoutToServer=True, stderrToServer=True)

batch_size = 32
num_classes = 10
epochs = 100
# data_augmentation = False
num_predictions = 20
save_dir = os.path.join(os.getcwd(), 'saved_models')
model_name = 'keras_cifar10_trained_model.h5'

# The data, shuffled and split between train and test sets:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Data normalization
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# Convert class vectors to binary class matrices.
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

# Construct a shared base net
input_data = Input(shape=x_train.shape[1:])
data = Conv2D(32, (3, 3), padding='same', input_shape=x_train.shape[1:])(input_data)
data = Activation('relu')(data)
data = Conv2D(32, (3, 3))(data)
data = Activation('relu')(data)
data = MaxPooling2D(pool_size=(2, 2))(data)
data = Dropout(0.25)(data)

data = Conv2D(64, (3, 3), padding='same')(data)
data = Activation('relu')(data)
data = Conv2D(64, (3, 3))(data)
data = Activation('relu')(data)
data = MaxPooling2D(pool_size=(2, 2))(data)
data = Dropout(0.25)(data)

data = Flatten()(data)
data = Dense(512)(data)
data = Activation('relu')(data)
output_data = Dropout(0.5)(data)
base_net = Model(input_data, output_data)

# Actual input of final net
train_input = Input(shape=x_train.shape[1:], name="x_train")
test_input = Input(shape=x_train.shape[1:], name="x_test")

train_output = base_net(train_input)
test_output = base_net(test_input)

# tensorflow backend required
aux_input = Input(shape=(num_classes,), name="y_train")
combined_loss = MMD(num_classes, [0.4, 0.6])([train_output, test_output, aux_input])
transfer_net = Model(inputs=[train_input, test_input, aux_input], outputs=[combined_loss])

# initiate RMSprop optimizer
opt = keras.optimizers.rmsprop(lr=0.0001, decay=1e-6)

# Let's train the model using RMSprop
# model.compile(loss='categorical_crossentropy',
#               optimizer=opt,
#               metrics=['accuracy'])

print("###Start compiling###")
transfer_net.compile(loss=None, optimizer=opt)

print("###Start fitting###")
transfer_net.fit({"x_train": x_train,
                  "x_test": x_test,
                  "y_train": y_train},
                 batch_size=batch_size,
                 epochs=epochs,
                 validation_data=(x_test, y_test),
                 shuffle=True)

"""
if not data_augmentation:
    print('Not using data augmentation.')
    model.fit(x_train, y_train,
              batch_size=batch_size,
              epochs=epochs,
              validation_data=(x_test, y_test),
              shuffle=True)
else:
    print('Using real-time data augmentation.')
    # This will do preprocessing and realtime data augmentation:
    datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=True,  # randomly flip images
        vertical_flip=False)  # randomly flip images

    # Compute quantities required for feature-wise normalization
    # (std, mean, and principal components if ZCA whitening is applied).
    datagen.fit(x_train)

    # Fit the model on the batches generated by datagen.flow().
    model.fit_generator(datagen.flow(x_train, y_train,
                                     batch_size=batch_size),
                        epochs=epochs,
                        validation_data=(x_test, y_test),
                        workers=4)
"""

# Save model and weights
if not os.path.isdir(save_dir):
    os.makedirs(save_dir)
model_path = os.path.join(save_dir, model_name)
transfer_net.save(model_path)
print('Saved trained model at %s ' % model_path)

# Score trained model.
scores = transfer_net.evaluate(x_test, y_test, verbose=1)
print('Test loss:', scores[0])
print('Test accuracy:', scores[1])

# pydevd.stoptrace()