"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.saving.file_editor import KerasFileEditor
from keras.src.saving.object_registration import CustomObjectScope
from keras.src.saving.object_registration import \
    CustomObjectScope as custom_object_scope
from keras.src.saving.object_registration import (get_custom_objects,
                                                  get_registered_name,
                                                  get_registered_object,
                                                  register_keras_serializable)
from keras.src.saving.saving_api import (load_model, load_weights, save_model,
                                         save_weights)
from keras.src.saving.serialization_lib import (deserialize_keras_object,
                                                serialize_keras_object)
