"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.types import DType as DType
from keras.src.types import Shape as Shape
from keras.src.types import Tensor as Tensor
