path: "tensorflow.keras.__internal__"
tf_module {
  member {
    name: "layers"
    mtype: "<type \'module\'>"
  }
  member {
    name: "legacy"
    mtype: "<type \'module\'>"
  }
  member_method {
    name: "enable_unsafe_deserialization"
    argspec: "args=[], varargs=None, keywords=None, defaults=None"
  }
}
