path: "tensorflow.keras.callbacks.experimental.UpdateEmbeddingCallback"
tf_class {
  is_instance: "<class \'keras.callbacks.UpdateEmbeddingCallback\'>"
  is_instance: "<class \'keras.utils.timed_threads.TimedThread\'>"
  is_instance: "<class \'keras.callbacks.Callback\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'dynamic_embedding_layer\', \'interval\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "is_alive"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "on_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_epoch_begin"
    argspec: "args=[\'self\', \'epoch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_epoch_end"
    argspec: "args=[\'self\', \'epoch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_interval"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "on_predict_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_predict_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_predict_begin"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_predict_end"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_test_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_test_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_test_begin"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_test_end"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_batch_begin"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_batch_end"
    argspec: "args=[\'self\', \'batch\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_begin"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "on_train_end"
    argspec: "args=[\'self\', \'logs\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "set_model"
    argspec: "args=[\'self\', \'model\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "set_params"
    argspec: "args=[\'self\', \'params\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "start"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "stop"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
