have_fun: false
memory_config:
  disabled: false
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
pull_request_opened:
  help: true
  summary: true
  code_review: true
include_drafts: true
ignore_patterns: []
