"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.legacy.preprocessing.text import (Tokenizer, hashing_trick,
                                                 one_hot,
                                                 text_to_word_sequence,
                                                 tokenizer_from_json)
