"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.dtype_policies import deserialize, get, serialize
from keras.src.dtype_policies.dtype_policy import (DTypePolicy,
                                                   FloatDTypePolicy,
                                                   QuantizedDTypePolicy,
                                                   QuantizedFloat8DTypePolicy)
from keras.src.dtype_policies.dtype_policy_map import DTypePolicyMap
