"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.tree.tree_api import (MAP_TO_NONE, assert_same_paths,
                                     assert_same_structure, flatten,
                                     flatten_with_path, is_nested,
                                     lists_to_tuples, map_shape_structure,
                                     map_structure, map_structure_up_to,
                                     pack_sequence_as, traverse)
