"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.optimizers.schedules.learning_rate_schedule import (
    CosineDecay, CosineDecayRestarts, ExponentialDecay, InverseTimeDecay,
    LearningRateSchedule, PiecewiseConstantDecay, PolynomialDecay, deserialize,
    serialize)
