# -*- coding: utf-8 -*-
import inspect
import keras_autodoc
import pathlib
import re
import shutil

from docs.structure import EXCLUDE
from docs.structure import PAGES
from docs.structure import template_hidden_np_implementation
from docs.structure import template_np_implementation
from keras.backend import numpy_backend

keras_dir = pathlib.Path(__file__).resolve().parents[1]


def post_process_signature(signature):
    parts = re.split(r'\.(?!\d)', signature)
    if len(parts) >= 4:
        if parts[1] == 'layers':
            signature = 'keras.layers.' + '.'.join(parts[3:])
        if parts[1] == 'utils':
            signature = 'keras.utils.' + '.'.join(parts[3:])
        if parts[1] == 'backend':
            signature = 'keras.backend.' + '.'.join(parts[3:])
    signature = signature.replace('keras_applications', 'keras.applications')
    signature = signature.replace('keras_preprocessing', 'keras.preprocessing')
    return signature


def add_np_implementation(function, docstring):
    np_implementation = getattr(numpy_backend, function.__name__)
    code = inspect.getsource(np_implementation)
    code_lines = code.split('\n')
    for i in range(len(code_lines)):
        if code_lines[i]:
            # if there is something on the line, add 8 spaces.
            code_lines[i] = '        ' + code_lines[i]
    code = '\n'.join(code_lines[:-1])

    if len(code_lines) < 10:
        section = template_np_implementation.replace('{{code}}', code)
    else:
        section = template_hidden_np_implementation.replace('{{code}}', code)
    return docstring.replace('{{np_implementation}}', section)


def preprocess_docstring(docstring, function, signature):
    if 'backend' in signature and '{{np_implementation}}' in docstring:
        docstring = add_np_implementation(function, docstring)
    return docstring

keras_team_url = 'https://github.com/keras-team'

project_url = {
        'keras': f'{keras_team_url}/keras/blob/master',
        'keras_applications': f'{keras_team_url}/keras-applications/blob/master',
        'keras_preprocessing': f'{keras_team_url}/keras-preprocessing/blob/master',
    }


def generate(dest_dir):
    template_dir = keras_dir / 'docs' / 'templates'
    keras_autodoc.generate(
        dest_dir,
        template_dir,
        PAGES,
        project_url,
        keras_dir / 'examples',
        EXCLUDE,
        post_process_signature=post_process_signature,
        preprocess_docstring=preprocess_docstring,
    )
    readme = (keras_dir / 'README.md').read_text()
    index = (template_dir / 'index.md').read_text()
    index = index.replace('{{autogenerated}}', readme[readme.find('##'):])
    (dest_dir / 'index.md').write_text(index, encoding='utf-8')
    shutil.copyfile(keras_dir / 'CONTRIBUTING.md', dest_dir / 'contributing.md')


if __name__ == '__main__':
    generate(keras_dir / 'docs' / 'sources')
