# DO NOT EDIT. Generated by api_gen.sh
from keras.api import (DTypePolicy, FloatDTypePolicy, Function, Initializer,
                       Input, InputSpec, KerasTensor, Layer, Loss, Metric,
                       Model, Operation, Optimizer, Quantizer, Regularizer,
                       Sequential, StatelessScope, SymbolicScope, Variable,
                       __version__, activations, applications, backend,
                       callbacks, config, constraints, datasets, device,
                       distribution, dtype_policies, export, initializers,
                       layers, legacy, losses, metrics, mixed_precision,
                       models, name_scope, ops, optimizers, preprocessing,
                       quantizers, random, regularizers, saving, tree, utils,
                       version, visualization, wrappers)

# END DO NOT EDIT.

import os  # isort: skip

# Add everything in /api/ to the module search path.
__path__.append(os.path.join(os.path.dirname(__file__), "api"))  # noqa: F405

# Don't pollute namespace.
del os


# Never autocomplete `.src` or `.api` on an imported keras object.
def __dir__():
    keys = dict.fromkeys((globals().keys()))
    keys.pop("src")
    keys.pop("api")
    return list(keys)


# Don't import `.src` or `.api` during `from keras import *`.
__all__ = [
    name
    for name in globals().keys()
    if not (name.startswith("_") or name in ("src", "api"))
]
