"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.losses import deserialize, get, serialize
from keras.src.losses.loss import Loss
from keras.src.losses.losses import (CTC, BinaryCrossentropy,
                                     BinaryFocalCrossentropy,
                                     CategoricalCrossentropy,
                                     CategoricalFocalCrossentropy,
                                     CategoricalHinge, Circle,
                                     CosineSimilarity, Dice, Hinge, Huber,
                                     KLDivergence, LogCosh, MeanAbsoluteError,
                                     MeanAbsolutePercentageError,
                                     MeanSquaredError,
                                     MeanSquaredLogarithmicError, Poisson,
                                     SparseCategoricalCrossentropy,
                                     SquaredHinge, Tversky,
                                     binary_crossentropy,
                                     binary_focal_crossentropy,
                                     categorical_crossentropy,
                                     categorical_focal_crossentropy,
                                     categorical_hinge, circle,
                                     cosine_similarity, ctc, dice, hinge,
                                     huber, kl_divergence, log_cosh,
                                     mean_absolute_error,
                                     mean_absolute_percentage_error,
                                     mean_squared_error,
                                     mean_squared_logarithmic_error, poisson,
                                     sparse_categorical_crossentropy,
                                     squared_hinge, tversky)
