name: auto-assignment

on:
  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  auto_assign:
    uses: keras-team/shared-workflows/.github/workflows/auto-assignment.yml@d9d8977425f512c21d72ace682b9fae6e4c5b901 # v1
    with:
      issue_assignees: 'maitry63,mrinalghoshh,dhantule'
