name: Test Docker Socket Mount

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  socket-mount-test:
    name: Docker Socket Mount Test
    runs-on: linux-x86-ct6e-44-1tpu

    # Use a minimal public container. The key is the 'options' block.
    container:
      image: ubuntu:latest
      options: -v /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Check if docker.sock is mounted
        run: |
          echo "Attempting to list the Docker socket inside the container..."
          ls -l /var/run/docker.sock
          echo "If the line above shows the file details, the mount was successful."

