name: Find Runner Service Account

# Trigger on push to master, pull requests, or new releases
on:
  push:
    branches: [ master ]
  pull_request:
  release:
    types: [created]

jobs:
  discover_service_account:
    name: Discover Service Account
    # The runner name is now hardcoded since we removed the manual input
    runs-on: linux-x86-ct6e-44-1tpu

    # Add a container block to satisfy the runner's security policy.
    # We use a standard Google Cloud SDK image which has gcloud pre-installed.
    container:
      image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
      # Using host networking makes it easier for the container to access
      # the host VM's metadata server to find the service account.
      options: --network host

    steps:
      - name: Print the configured GCP Service Account
        run: |
          echo "Querying the GCP metadata server from within a container..."
          echo "The active account shown below is the one used by the runner's host VM."
          gcloud auth list

