name: Find Runner Service Account

# This allows you to run the workflow manually from the Actions tab
on:
  push:
    branches: [ master ]
  pull_request:
  release:
    types: [created]

jobs:
  discover_service_account:
    name: Discover Service Account
    # This line tells the job to run on the specific runner you provide
    runs-on: linux-x86-ct6e-44-1tpu

    steps:
      - name: Print the configured GCP Service Account
        run: |
          echo "Querying the GCP metadata server to find the active Service Account..."
          gcloud auth list