name: 'Labeler'
on:
  issues:
    types: [edited,opened]
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [opened, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const script = require('./\.github/workflows/scripts/labeler.js')
            script({github, context})