name: 'PR Contributor Agreement'

on:
  pull_request:
    types:
      - 'opened'
      - 'edited'
      - 'reopened'
      - 'synchronize'

permissions:
  contents: 'read'
  pull-requests: 'read'

jobs:
  verify:
    if: github.repository == 'keras-team/keras'
    uses: keras-team/shared-workflows/.github/workflows/pr-contributor-terms.yml@1ff60fd615b03a85abdffac6d7cbe390988bb305 # v1
