name: TPU Tests

on:
  push:
    branches: [ master ]
  pull_request:
  release:
    types: [created]

permissions:
  contents: read # Only read permission is needed for checkout

jobs:
  test-on-tpu-runner:
    name: Test on TPU Runner
    # This job runs on the self-hosted TPU runner.
    # It assumes the runner is already authenticated to Google Cloud's Artifact Registry.
    # The associated service account 'workload-keras-sa@ml-velocity-actions-production.iam.gserviceaccount.com'
    # must have the "Artifact Registry Reader" role for this to work.
    runs-on: linux-x86-ct6e-44-1tpu

    # CRITICAL: Use the pre-built container image from Google Artifact Registry.
    # The runner's Docker daemon will pull this image before starting the job.
    container:
      image: us-central1-docker.pkg.dev/gtech-rmi-dev/keras-docker-images/keras-jax-tpu-amd64:latest
      options: --privileged --network host

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # We need the code available inside the container's workspace to run tests.

      - name: Run Verification and Tests
        run: |
          echo "Successfully running inside the custom container from GAR!"
          echo "Current working directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Verifying JAX installation..."
          python3 -c "import jax; print(f'JAX backend: {jax.default_backend()}'); print(f'JAX devices: {jax.devices()}')"