name: Trigger GPU & TPU Tests

on:
  pull_request:
    types: [labeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  trigger:
    name: Trigger and Remove Label
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled' && github.event.label.name == 'kokoro:force-run'
    steps:
      - name: Trigger GPU Tests
        uses: ./.github/workflows/gpu_tests.yml

      - name: Trigger TPU Tests
        uses: ./.github/workflows/tpu_tests.yml

      - name: Remove Label
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'kokoro:force-run'
            });
