name: Zizmor
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  zizmor:
    name: GitHub Actions Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv dependencies
        # zizmor: ignore[impostor-commit, mismatched-version-comment]
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Run zizmor
        run:  uvx zizmor --format=github .github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
