from keras.src.backend.common.name_scope import name_scope
from keras.src.backend.numpy import core
from keras.src.backend.numpy import image
from keras.src.backend.numpy import linalg
from keras.src.backend.numpy import math
from keras.src.backend.numpy import nn
from keras.src.backend.numpy import numpy
from keras.src.backend.numpy import random
from keras.src.backend.numpy.core import IS_THREAD_SAFE
from keras.src.backend.numpy.core import SUPPORTS_COMPLEX_DTYPES
from keras.src.backend.numpy.core import SUPPORTS_RAGGED_TENSORS
from keras.src.backend.numpy.core import SUPPORTS_SPARSE_TENSORS
from keras.src.backend.numpy.core import Variable
from keras.src.backend.numpy.core import cast
from keras.src.backend.numpy.core import compute_output_spec
from keras.src.backend.numpy.core import cond
from keras.src.backend.numpy.core import convert_to_numpy
from keras.src.backend.numpy.core import convert_to_tensor
from keras.src.backend.numpy.core import device_scope
from keras.src.backend.numpy.core import get_memory_info
from keras.src.backend.numpy.core import is_tensor
from keras.src.backend.numpy.core import random_seed_dtype
from keras.src.backend.numpy.core import shape
from keras.src.backend.numpy.core import vectorized_map
from keras.src.backend.numpy.numpy import absolute
from keras.src.backend.numpy.numpy import add
from keras.src.backend.numpy.numpy import all
from keras.src.backend.numpy.numpy import allclose
from keras.src.backend.numpy.numpy import amax
from keras.src.backend.numpy.numpy import amin
from keras.src.backend.numpy.numpy import angle
from keras.src.backend.numpy.numpy import any
from keras.src.backend.numpy.numpy import append
from keras.src.backend.numpy.numpy import arange
from keras.src.backend.numpy.numpy import arccos
from keras.src.backend.numpy.numpy import arccosh
from keras.src.backend.numpy.numpy import arcsin
from keras.src.backend.numpy.numpy import arcsinh
from keras.src.backend.numpy.numpy import arctan
from keras.src.backend.numpy.numpy import arctan2
from keras.src.backend.numpy.numpy import arctanh
from keras.src.backend.numpy.numpy import argmax
from keras.src.backend.numpy.numpy import argmin
from keras.src.backend.numpy.numpy import argpartition
from keras.src.backend.numpy.numpy import argsort
from keras.src.backend.numpy.numpy import array
from keras.src.backend.numpy.numpy import array_split
from keras.src.backend.numpy.numpy import average
from keras.src.backend.numpy.numpy import bartlett
from keras.src.backend.numpy.numpy import bincount
from keras.src.backend.numpy.numpy import bitwise_and
from keras.src.backend.numpy.numpy import bitwise_invert
from keras.src.backend.numpy.numpy import bitwise_left_shift
from keras.src.backend.numpy.numpy import bitwise_not
from keras.src.backend.numpy.numpy import bitwise_or
from keras.src.backend.numpy.numpy import bitwise_right_shift
from keras.src.backend.numpy.numpy import bitwise_xor
from keras.src.backend.numpy.numpy import blackman
from keras.src.backend.numpy.numpy import broadcast_to
from keras.src.backend.numpy.numpy import cbrt
from keras.src.backend.numpy.numpy import ceil
from keras.src.backend.numpy.numpy import clip
from keras.src.backend.numpy.numpy import concatenate
from keras.src.backend.numpy.numpy import conjugate
from keras.src.backend.numpy.numpy import copy
from keras.src.backend.numpy.numpy import corrcoef
from keras.src.backend.numpy.numpy import correlate
from keras.src.backend.numpy.numpy import cos
from keras.src.backend.numpy.numpy import cosh
from keras.src.backend.numpy.numpy import count_nonzero
from keras.src.backend.numpy.numpy import cross
from keras.src.backend.numpy.numpy import cumprod
from keras.src.backend.numpy.numpy import cumsum
from keras.src.backend.numpy.numpy import deg2rad
from keras.src.backend.numpy.numpy import diag
from keras.src.backend.numpy.numpy import diagflat
from keras.src.backend.numpy.numpy import diagonal
from keras.src.backend.numpy.numpy import diff
from keras.src.backend.numpy.numpy import digitize
from keras.src.backend.numpy.numpy import divide
from keras.src.backend.numpy.numpy import divide_no_nan
from keras.src.backend.numpy.numpy import dot
from keras.src.backend.numpy.numpy import dsplit
from keras.src.backend.numpy.numpy import dstack
from keras.src.backend.numpy.numpy import einsum
from keras.src.backend.numpy.numpy import empty
from keras.src.backend.numpy.numpy import empty_like
from keras.src.backend.numpy.numpy import equal
from keras.src.backend.numpy.numpy import exp
from keras.src.backend.numpy.numpy import exp2
from keras.src.backend.numpy.numpy import expand_dims
from keras.src.backend.numpy.numpy import expm1
from keras.src.backend.numpy.numpy import eye
from keras.src.backend.numpy.numpy import fabs
from keras.src.backend.numpy.numpy import flip
from keras.src.backend.numpy.numpy import fliplr
from keras.src.backend.numpy.numpy import flipud
from keras.src.backend.numpy.numpy import floor
from keras.src.backend.numpy.numpy import floor_divide
from keras.src.backend.numpy.numpy import fmax
from keras.src.backend.numpy.numpy import fmin
from keras.src.backend.numpy.numpy import fmod
from keras.src.backend.numpy.numpy import full
from keras.src.backend.numpy.numpy import full_like
from keras.src.backend.numpy.numpy import gcd
from keras.src.backend.numpy.numpy import geomspace
from keras.src.backend.numpy.numpy import greater
from keras.src.backend.numpy.numpy import greater_equal
from keras.src.backend.numpy.numpy import hamming
from keras.src.backend.numpy.numpy import hanning
from keras.src.backend.numpy.numpy import heaviside
from keras.src.backend.numpy.numpy import histogram
from keras.src.backend.numpy.numpy import hsplit
from keras.src.backend.numpy.numpy import hstack
from keras.src.backend.numpy.numpy import hypot
from keras.src.backend.numpy.numpy import i0
from keras.src.backend.numpy.numpy import identity
from keras.src.backend.numpy.numpy import imag
from keras.src.backend.numpy.numpy import inner
from keras.src.backend.numpy.numpy import isclose
from keras.src.backend.numpy.numpy import isfinite
from keras.src.backend.numpy.numpy import isin
from keras.src.backend.numpy.numpy import isinf
from keras.src.backend.numpy.numpy import isnan
from keras.src.backend.numpy.numpy import isneginf
from keras.src.backend.numpy.numpy import isposinf
from keras.src.backend.numpy.numpy import isreal
from keras.src.backend.numpy.numpy import kaiser
from keras.src.backend.numpy.numpy import kron
from keras.src.backend.numpy.numpy import lcm
from keras.src.backend.numpy.numpy import ldexp
from keras.src.backend.numpy.numpy import left_shift
from keras.src.backend.numpy.numpy import less
from keras.src.backend.numpy.numpy import less_equal
from keras.src.backend.numpy.numpy import linspace
from keras.src.backend.numpy.numpy import log
from keras.src.backend.numpy.numpy import log1p
from keras.src.backend.numpy.numpy import log2
from keras.src.backend.numpy.numpy import log10
from keras.src.backend.numpy.numpy import logaddexp
from keras.src.backend.numpy.numpy import logaddexp2
from keras.src.backend.numpy.numpy import logical_and
from keras.src.backend.numpy.numpy import logical_not
from keras.src.backend.numpy.numpy import logical_or
from keras.src.backend.numpy.numpy import logical_xor
from keras.src.backend.numpy.numpy import logspace
from keras.src.backend.numpy.numpy import matmul
from keras.src.backend.numpy.numpy import max
from keras.src.backend.numpy.numpy import maximum
from keras.src.backend.numpy.numpy import mean
from keras.src.backend.numpy.numpy import median
from keras.src.backend.numpy.numpy import meshgrid
from keras.src.backend.numpy.numpy import min
from keras.src.backend.numpy.numpy import minimum
from keras.src.backend.numpy.numpy import mod
from keras.src.backend.numpy.numpy import moveaxis
from keras.src.backend.numpy.numpy import multiply
from keras.src.backend.numpy.numpy import nan_to_num
from keras.src.backend.numpy.numpy import nanargmax
from keras.src.backend.numpy.numpy import nanargmin
from keras.src.backend.numpy.numpy import nancumprod
from keras.src.backend.numpy.numpy import nancumsum
from keras.src.backend.numpy.numpy import nanmax
from keras.src.backend.numpy.numpy import nanmean
from keras.src.backend.numpy.numpy import nanmedian
from keras.src.backend.numpy.numpy import nanmin
from keras.src.backend.numpy.numpy import nanpercentile
from keras.src.backend.numpy.numpy import nanprod
from keras.src.backend.numpy.numpy import nanquantile
from keras.src.backend.numpy.numpy import nanstd
from keras.src.backend.numpy.numpy import nansum
from keras.src.backend.numpy.numpy import nanvar
from keras.src.backend.numpy.numpy import ndim
from keras.src.backend.numpy.numpy import negative
from keras.src.backend.numpy.numpy import nextafter
from keras.src.backend.numpy.numpy import nonzero
from keras.src.backend.numpy.numpy import not_equal
from keras.src.backend.numpy.numpy import ones
from keras.src.backend.numpy.numpy import ones_like
from keras.src.backend.numpy.numpy import outer
from keras.src.backend.numpy.numpy import pad
from keras.src.backend.numpy.numpy import percentile
from keras.src.backend.numpy.numpy import power
from keras.src.backend.numpy.numpy import prod
from keras.src.backend.numpy.numpy import ptp
from keras.src.backend.numpy.numpy import quantile
from keras.src.backend.numpy.numpy import rad2deg
from keras.src.backend.numpy.numpy import ravel
from keras.src.backend.numpy.numpy import real
from keras.src.backend.numpy.numpy import reciprocal
from keras.src.backend.numpy.numpy import repeat
from keras.src.backend.numpy.numpy import reshape
from keras.src.backend.numpy.numpy import right_shift
from keras.src.backend.numpy.numpy import roll
from keras.src.backend.numpy.numpy import rot90
from keras.src.backend.numpy.numpy import round
from keras.src.backend.numpy.numpy import searchsorted
from keras.src.backend.numpy.numpy import select
from keras.src.backend.numpy.numpy import sign
from keras.src.backend.numpy.numpy import signbit
from keras.src.backend.numpy.numpy import sin
from keras.src.backend.numpy.numpy import sinc
from keras.src.backend.numpy.numpy import sinh
from keras.src.backend.numpy.numpy import size
from keras.src.backend.numpy.numpy import slogdet
from keras.src.backend.numpy.numpy import sort
from keras.src.backend.numpy.numpy import split
from keras.src.backend.numpy.numpy import sqrt
from keras.src.backend.numpy.numpy import square
from keras.src.backend.numpy.numpy import squeeze
from keras.src.backend.numpy.numpy import stack
from keras.src.backend.numpy.numpy import std
from keras.src.backend.numpy.numpy import subtract
from keras.src.backend.numpy.numpy import sum
from keras.src.backend.numpy.numpy import swapaxes
from keras.src.backend.numpy.numpy import take
from keras.src.backend.numpy.numpy import take_along_axis
from keras.src.backend.numpy.numpy import tan
from keras.src.backend.numpy.numpy import tanh
from keras.src.backend.numpy.numpy import tensordot
from keras.src.backend.numpy.numpy import tile
from keras.src.backend.numpy.numpy import trace
from keras.src.backend.numpy.numpy import transpose
from keras.src.backend.numpy.numpy import trapezoid
from keras.src.backend.numpy.numpy import tri
from keras.src.backend.numpy.numpy import tril
from keras.src.backend.numpy.numpy import triu
from keras.src.backend.numpy.numpy import true_divide
from keras.src.backend.numpy.numpy import trunc
from keras.src.backend.numpy.numpy import unique
from keras.src.backend.numpy.numpy import unravel_index
from keras.src.backend.numpy.numpy import vander
from keras.src.backend.numpy.numpy import var
from keras.src.backend.numpy.numpy import vdot
from keras.src.backend.numpy.numpy import vectorize
from keras.src.backend.numpy.numpy import view
from keras.src.backend.numpy.numpy import vsplit
from keras.src.backend.numpy.numpy import vstack
from keras.src.backend.numpy.numpy import where
from keras.src.backend.numpy.numpy import zeros
from keras.src.backend.numpy.numpy import zeros_like
from keras.src.backend.numpy.rnn import bidirectional_gru
from keras.src.backend.numpy.rnn import bidirectional_lstm
from keras.src.backend.numpy.rnn import cudnn_ok
from keras.src.backend.numpy.rnn import gru
from keras.src.backend.numpy.rnn import lstm
from keras.src.backend.numpy.rnn import rnn
