"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras.src.backend.common.dtypes import result_type
from keras.src.backend.common.global_state import clear_session
from keras.src.backend.common.keras_tensor import is_keras_tensor
from keras.src.backend.common.variables import (is_float_dtype, is_int_dtype,
                                                standardize_dtype)
from keras.src.backend.config import (backend, epsilon, floatx,
                                      image_data_format, set_epsilon,
                                      set_floatx, set_image_data_format)
from keras.src.legacy.backend import (abs, all, any, arange, argmax, argmin,
                                      batch_dot, batch_flatten,
                                      batch_get_value, batch_normalization,
                                      batch_set_value, bias_add,
                                      binary_crossentropy,
                                      binary_focal_crossentropy, cast,
                                      cast_to_floatx, categorical_crossentropy,
                                      categorical_focal_crossentropy, clip,
                                      concatenate, constant, conv1d, conv2d,
                                      conv2d_transpose, conv3d, cos,
                                      count_params, ctc_batch_cost, ctc_decode,
                                      ctc_label_dense_to_sparse, cumprod,
                                      cumsum, depthwise_conv2d, dot, dropout,
                                      dtype, elu, equal, eval, exp,
                                      expand_dims, eye, flatten, foldl, foldr,
                                      gather, get_value, gradients, greater,
                                      greater_equal, hard_sigmoid, in_top_k,
                                      int_shape, is_sparse, l2_normalize, less,
                                      less_equal, log, map_fn, max, maximum,
                                      mean, min, minimum,
                                      moving_average_update, name_scope, ndim,
                                      not_equal, one_hot, ones, ones_like,
                                      permute_dimensions, pool2d, pool3d, pow,
                                      prod, random_bernoulli, random_normal,
                                      random_normal_variable, random_uniform,
                                      random_uniform_variable, relu, repeat,
                                      repeat_elements, reshape, resize_images,
                                      resize_volumes, reverse, rnn, round,
                                      separable_conv2d, set_value, shape,
                                      sigmoid, sign, sin, softmax, softplus,
                                      softsign,
                                      sparse_categorical_crossentropy,
                                      spatial_2d_padding, spatial_3d_padding,
                                      sqrt, square, squeeze, stack, std,
                                      stop_gradient, sum, switch, tanh,
                                      temporal_padding, tile, to_dense,
                                      transpose, truncated_normal, update,
                                      update_add, update_sub, var, variable,
                                      zeros, zeros_like)
from keras.src.utils.naming import get_uid
